### ISSUE TITLE
pushData assertion failed

### ISSUE THREAD

**Issue by taxilly** [josefnpat/LoverNet#22]
I'm able to get to get a clients/server connection,
```
1523495724 [Server:start] Starting Server on port 19870
1523495724 [Client:start] Starting Client on port 19870
1523495724 [Server:event] Connect: 127.0.0.1:59605 [InvalidName8147]
```
But my following code (specifically the `Client.ln\pushData()`) :(
```moonscript
Client.start = () ->
  Client.ln = lovernetlib.new()
  Client.ln\addOp('whoami')
  Client.ln\pushData('whomai',{name:'Dennis Ritchie'})
```
```moonscript
Server.start = () ->
  Server.ln = lovernetlib.new({type: lovernetlib.mode.server})
  Server.ln\addOp('whoami')
  Server.ln\addValidateOnServer('whoami',{name:'string'})
  Server.ln\addProcessOnServer 'whoami', (peer,arg,storage) =>
    user = @getUser(peer)
    user.name = arg.name
```
Gives the following error:
![2018-04-12-021934_1366x768_scrot](https://user-images.githubusercontent.com/13081443/38651327-89eb1578-3df8-11e8-82de-a2321ba75ba1.png)

Commenting out line 327 gives:
```
1523495724 [Server:error] Op.f `whomai` not in ops table: whomai
```
I ran `x\hasOp('whoami')` on both the server and client and they both have the whoami function, so I have no idea why I'm getting an error... Point me in the right direction?

**Comment by taxilly** [comment]
No less than 2 minutes after posting I realised `whoami` was actually spelt `who*m*ai` in the wiki, damn copypasting.

**Comment by josefnpat** [comment]
@ttxi I have started development on a project that is using lovernet, so there should be more support for this. Were you able to make a game of some sort? :)

**Comment by josefnpat** [comment]
thanks for pointing out the typo - I've updated the wiki.
